/* eslint-disable react-refresh/only-export-components */
import { CalendarDays, CircleUser, House, Landmark, LibraryBig, Settings, UsersRound } from "lucide-react"
import { assets } from "./assets/assets"

export const DashboardNavLinks = () => {
  return [
    { icon: <House size={18} />, label: "Dashboard", url: "/dashboard/home" },
    {
      icon: <UsersRound scale={18} />,
      label: "Members",
      url: "/dashboard/members",
    },
    {
      icon: <Landmark size={18} />,
      label: "Financial",
      url: "/dashboard/financials",
    },
    {
      icon: <LibraryBig size={18} />,
      label: "Publications",
      url: "/dashboard/publications",
    },
    {
      icon: <Settings size={18} />,
      label: "CPD Points",
      url: "/dashboard/cpd-points",
    },
    {
      icon: <CalendarDays size={18} />,
      label: "Events",
      url: "/dashboard/events",
    },
    {
      icon: <CircleUser size={18} />,
      label: "Profile",
      url: "/dashboard/profile/personalInfo",
    },
  ]
}

export const safetyTip = [
  {
    id: 1,
    icon: assets.check_icon,
    content: "Always verify patient identity before scan",
    safetyType: "Professional & Legal Safety",
  },
  {
    id: 2,
    icon: assets.danger_icon,
    content: "Use the ALARA principle (As Low As Reason)",
    safetyType: "Patient Handling & General Physical Safety",
  },
  {
    id: 3,
    icon: assets.signal_icon,
    content: "AI-assisted imaging gaining adoption",
    safetyType: "Mental Health & Psychological Safety",
  },
  {
    id: 4,
    icon: assets.check_icon,
    content: "Disinfect probes after each use",
    safetyType: "Radiation & Equipment Safety",
  },
  {
    id: 5,
    icon: assets.brain_icon,
    content: "Elastography rising in liver diagnostics",
    safetyType: "Infection Control & Hygiene Safety",
  },
  {
    id: 6,
    icon: assets.heart_outline,
    content: "Avoid excessive pressure during transducer use",
    safetyType: "Ergonomic Safety",
  },
]

export const allFundedAccount = [
  {
    userId: "1245-565656",
    name: "Joyce Arthur",
    email: "joycearthur2041@gmail.com",
    challenge: "Swift",
    fundedAmount: "$5,000",
    status: "Suspended",
  },
  {
    userId: "5656-4343434",
    name: "Marylin Brown",
    email: "marybrown@gmail.com",
    challenge: "Evaluation",
    fundedAmount: "$8,000",
    status: "Active",
  },
  {
    userId: "9021-884512",
    name: "Kwabena Owusu",
    email: "kwabenaowusu@gmail.com",
    challenge: "Trufunder Plus",
    fundedAmount: "$10,000",
    status: "Pending",
  },
  {
    userId: "1102-347912",
    name: "Sarah Addo",
    email: "sarahaddo2025@gmail.com",
    challenge: "One-Step",
    fundedAmount: "$15,000",
    status: "Terminated",
  },
  {
    userId: "7755-331199",
    name: "Prince Boateng",
    email: "princeb@gmail.com",
    challenge: "Synthetics",
    fundedAmount: "$12,500",
    status: "Suspended",
  },
  {
    userId: "4442-667812",
    name: "Deloris Owusu",
    email: "delorisowusu@gmail.com",
    challenge: "Swift",
    fundedAmount: "$6,000",
    status: "Active",
  },
  {
    userId: "8853-984412",
    name: "Felix Adjei",
    email: "felix.adjei@hotmail.com",
    challenge: "Evaluation",
    fundedAmount: "$7,000",
    status: "Pending",
  },
  {
    userId: "2349-765234",
    name: "Rebecca Asante",
    email: "rebecca.asante@gmail.com",
    challenge: "Trufunder Plus",
    fundedAmount: "$20,000",
    status: "Terminated",
  },
  {
    userId: "3265-845212",
    name: "Nana Ama Serwaa",
    email: "nanaama.serwaa@gmail.com",
    challenge: "One-Step",
    fundedAmount: "$5,500",
    status: "Active",
  },
  {
    userId: "7812-334455",
    name: "Kweku Mensah",
    email: "kwekumensah1999@yahoo.com",
    challenge: "Synthetics",
    fundedAmount: "$9,000",
    status: "Suspended",
  },
]

export const upcomingEvent = [
  {
    id: 1,
    event: "Cardiac Imaging Masterclass",
    location: "University of Ghana",
    type: "Workshop",
    date: "2025-06-11",
    CPDPoints: "4",
    status: "Open",
    image: assets.heart_icon,
  },
  {
    id: 2,
    event: "Advanced Doppler Techniques Workshop",
    location: "Online",
    type: "Webinar",
    date: "2025-03-24",
    CPDPoints: "6",
    status: "Limited Spots",
    image: assets.video_icon,
  },
  {
    id: 3,
    event: "Annual General Conference",
    location: "Bank Of Ghana Auditorium",
    type: "Conference",
    date: "2024-07-04",
    CPDPoints: "10",
    status: "Open",
    image: assets.conference_icon,
  },
  {
    id: 4,
    event: "Cardiac Imaging Masterclass",
    location: "Great Hall",
    type: "Webinar",
    date: "2025-01-04",
    CPDPoints: "5",
    status: "Limited Spots",
    image: assets.video_icon,
  },
  {
    id: 5,
    event: "Annual General Conference",
    location: "Santasi",
    type: "Workshop",
    date: "2025-11-11",
    CPDPoints: "4",
    status: "Open",
    image: assets.heart_icon,
  },
]

export const cpdActivities = [
  {
    id: "1",
    activity_title: "Webinar on Ethical Practices in Medicine",
    activity_type: "Webinar",
    provider_name: "Global Medical Ethics Org",
    start_date: "2025-03-01",
    end_date: "2025-03-01",
    duration_hours: 2,
    points_earned: 2,
    is_verified: true,
    certificate_url: "https://example.com/certificates/ethics.pdf",
    status: "Pending",
  },
  {
    id: "2",
    activity_title: "First Aid Workshop",
    activity_type: "Workshop",
    provider_name: "Red Cross International",
    start_date: "2025-02-10",
    end_date: "2025-02-12",
    duration_hours: 6,
    points_earned: 6,
    is_verified: false,
    certificate_url: "",
    status: "Approved",
  },
  {
    id: "3",
    activity_title: "Advanced Life Support Course",
    activity_type: "Course",
    provider_name: "Health Skills Academy",
    start_date: "2025-01-15",
    end_date: "2025-01-17",
    duration_hours: 10,
    points_earned: 10,
    is_verified: true,
    certificate_url: "https://example.com/certificates/als.pdf",
    status: "Rejected",
  },
  {
    id: "4",
    activity_title: "Community Health Outreach Participation",
    activity_type: "Volunteering",
    provider_name: "Ministry of Health",
    start_date: "2025-04-05",
    end_date: "2025-04-07",
    duration_hours: 5,
    points_earned: 5,
    is_verified: false,
    certificate_url: "",
    status: "Pending",
  },
  {
    id: "5",
    activity_title: "Online Training on Patient Safety",
    activity_type: "Online Course",
    provider_name: "SafeCare Academy",
    start_date: "2025-05-10",
    end_date: "2025-05-12",
    duration_hours: 3,
    points_earned: 3,
    is_verified: true,
    certificate_url: "https://example.com/certificates/safety.pdf",
    status: "Pending",
  },
  {
    id: "6",
    activity_title: "Healthcare Data Management Conference",
    activity_type: "Conference",
    provider_name: "HealthTech Summit 2025",
    start_date: "2025-06-02",
    end_date: "2025-06-03",
    duration_hours: 8,
    points_earned: 8,
    is_verified: false,
    certificate_url: "",
    status: "Approved",
  },
  {
    id: "7",
    activity_title: "Mentorship Program for Junior Staff",
    activity_type: "Mentoring",
    provider_name: "GARMS Leadership Program",
    start_date: "2025-01-01",
    end_date: "2025-06-30",
    duration_hours: 15,
    points_earned: 15,
    is_verified: true,
    certificate_url: "https://example.com/certificates/mentorship.pdf",
    status: "Approved",
  },
  {
    id: "8",
    activity_title: "Research on Community Disease Patterns",
    activity_type: "Research",
    provider_name: "University of Health Sciences",
    start_date: "2025-03-01",
    end_date: "2025-06-01",
    duration_hours: 12,
    points_earned: 12,
    is_verified: true,
    certificate_url: "https://example.com/certificates/research.pdf",
    status: "Rejected",
  },
  {
    id: "9",
    activity_title: "Infection Control Workshop",
    activity_type: "Workshop",
    provider_name: "WHO Certified Trainer",
    start_date: "2025-07-10",
    end_date: "2025-07-11",
    duration_hours: 4,
    points_earned: 4,
    is_verified: false,
    certificate_url: "",
    status: "Pending",
  },
  {
    id: "10",
    activity_title: "eBook: Emerging Trends in Nursing",
    activity_type: "Publication",
    provider_name: "Nursing Times",
    start_date: "2025-06-15",
    end_date: "2025-06-15",
    duration_hours: 1.5,
    points_earned: 1.5,
    is_verified: true,
    certificate_url: "https://example.com/certificates/nursing_trends.pdf",
    status: "Approved",
  },
]

export const outstandingPayments = [
  {
    id: 1,
    description: "Annual Subscription 2025",
    amount: 300,
    dueDate: "2025-12-31",
    status: "Unpaid",
  },
  {
    id: 2,
    description: "CPD Workshop - Tech Ethics",
    amount: 120,
    dueDate: "2025-08-10",
    status: "Overdue",
  },
  {
    id: 3,
    description: "Regional Conference 2025",
    amount: 250,
    dueDate: "2025-09-15",
    status: "Unpaid",
  },
  {
    id: 4,
    description: "Professional Dues 2025",
    amount: 180,
    dueDate: "2025-11-30",
    status: "Unpaid",
  },
  {
    id: 5,
    description: "Annual Dinner Ticket",
    amount: 75,
    dueDate: "2025-10-01",
    status: "Overdue",
  },
  {
    id: 6,
    description: "CPD Seminar - AI in Health",
    amount: 90,
    dueDate: "2025-07-30",
    status: "Overdue",
  },
  {
    id: 7,
    description: "Monthly Membership Renewal",
    amount: 50,
    dueDate: "2025-08-01",
    status: "Unpaid",
  },
  {
    id: 8,
    description: "Leadership Training",
    amount: 150,
    dueDate: "2025-09-20",
    status: "Unpaid",
  },
  {
    id: 9,
    description: "Advanced Research Workshop",
    amount: 200,
    dueDate: "2025-08-25",
    status: "Unpaid",
  },
  {
    id: 10,
    description: "Health Compliance Fee",
    amount: 60,
    dueDate: "2025-07-15",
    status: "Overdue",
  },
]

export const paymentHistory = [
  {
    id: 1,
    title: "Annual Subscription 2024",
    amount: 300,
    datePaid: "2024-12-20",
    transactionId: "TXN0018392",
    method: "Mobile Money",
  },
  {
    id: 2,
    title: "Workshop Fee - Robotics",
    amount: 200,
    datePaid: "2024-11-12",
    transactionId: "TXN0017284",
    method: "Visa",
  },
  {
    id: 3,
    title: "Regional Conference 2024",
    amount: 275,
    datePaid: "2024-10-01",
    transactionId: "TXN0018453",
    method: "Paystack",
  },
  {
    id: 4,
    title: "Monthly Membership - August",
    amount: 50,
    datePaid: "2024-08-05",
    transactionId: "TXN0016483",
    method: "MasterCard",
  },
  {
    id: 5,
    title: "Health Compliance Fee",
    amount: 60,
    datePaid: "2024-09-15",
    transactionId: "TXN0017965",
    method: "Mobile Money",
  },
  {
    id: 6,
    title: "Annual Dinner Ticket",
    amount: 75,
    datePaid: "2024-12-05",
    transactionId: "TXN0017450",
    method: "Visa",
  },
  {
    id: 7,
    title: "CPD Ethics Training",
    amount: 100,
    datePaid: "2024-07-28",
    transactionId: "TXN0017209",
    method: "Paystack",
  },
  {
    id: 8,
    title: "AI in Health Workshop",
    amount: 90,
    datePaid: "2024-10-25",
    transactionId: "TXN0017120",
    method: "MasterCard",
  },
  {
    id: 9,
    title: "Leadership Course",
    amount: 150,
    datePaid: "2024-09-30",
    transactionId: "TXN0017593",
    method: "Mobile Money",
  },
  {
    id: 10,
    title: "Advanced CPD Training",
    amount: 180,
    datePaid: "2024-08-20",
    transactionId: "TXN0018011",
    method: "Visa",
  },
]

export const memberPublications = [
  {
    _id: "pub1",
    title: "Effects of Ultrasound Imaging in Rural Healthcare",
    category: "Research",
    status: "Draft",
    createdAt: "2025-07-20T10:30:00Z",
    reviewsCount: 0,
  },
  {
    _id: "pub2",
    title: "Case Study: Pediatric Liver Abnormality",
    category: "Case",
    status: "Pending",
    createdAt: "2025-07-18T14:00:00Z",
    reviewsCount: 1,
  },
  {
    _id: "pub3",
    title: "Comparative Study of MRI vs CT Scan",
    category: "Research",
    status: "Approved",
    createdAt: "2025-07-15T09:45:00Z",
    reviewsCount: 4,
  },
  {
    _id: "pub4",
    title: "Case Review: Gallbladder Stone in Male Patient",
    category: "Case",
    status: "Rejected",
    createdAt: "2025-07-12T08:20:00Z",
    reviewsCount: 2,
  },
  {
    _id: "pub5",
    title: "Sonographic Features of Ectopic Pregnancy",
    category: "Research",
    status: "Approved",
    createdAt: "2025-07-10T13:15:00Z",
    reviewsCount: 5,
  },
  {
    _id: "pub6",
    title: "Case: Appendicitis in Teenage Patient",
    category: "Case",
    status: "Draft",
    createdAt: "2025-07-08T11:10:00Z",
    reviewsCount: 0,
  },
  {
    _id: "pub7",
    title: "Study on Doppler Waveforms in Hypertension",
    category: "Research",
    status: "Pending",
    createdAt: "2025-07-05T15:30:00Z",
    reviewsCount: 1,
  },
  {
    _id: "pub8",
    title: "Case Report: Brain Lesion in Elderly Patient",
    category: "Case",
    status: "Approved",
    createdAt: "2025-07-01T16:45:00Z",
    reviewsCount: 3,
  },
  {
    _id: "pub9",
    title: "Analysis of Sonography in Early Cancer Detection",
    category: "Research",
    status: "Rejected",
    createdAt: "2025-06-28T12:00:00Z",
    reviewsCount: 2,
  },
  {
    _id: "pub10",
    title: "Case of Misdiagnosed Gallstones",
    category: "Case",
    status: "Draft",
    createdAt: "2025-06-25T17:00:00Z",
    reviewsCount: 0,
  },
]

export const membersList = [
  {
    profileImage: assets.dummy_profile,
    memberId: "2455650909087",
    name: "Banahene Owusu Gideon",
    email: "banaheneowusu26@gmail.com",
    gender: "Male",
    cpdPoints: 20,
    region: "Ashanti",
    roles: "Intern",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "1952853902041",
    name: "Akosua Mensimah Amankwah",
    email: "akosua.amankwah98@gmail.com",
    gender: "Female",
    cpdPoints: 35,
    region: "Greater Accra",
    roles: "Licensed",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "3030193847291",
    name: "Kwame Nkrumah Tetteh",
    email: "nkrumah.tetteh@gmail.com",
    gender: "Male",
    cpdPoints: 12,
    region: "Eastern",
    roles: "Student",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "5802947123841",
    name: "Linda Asiedu",
    email: "linda.asiedu@outlook.com",
    gender: "Female",
    cpdPoints: 27,
    region: "Volta",
    roles: "Intern",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "4293850193847",
    name: "Yaw Opoku Frimpong",
    email: "yaw.opoku@garms.org",
    gender: "Male",
    cpdPoints: 50,
    region: "Ashanti",
    roles: "Licensed",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "8459203847102",
    name: "Esi Konadu Serwaa",
    email: "esi.serwaa@yahoo.com",
    gender: "Female",
    cpdPoints: 16,
    region: "Central",
    roles: "Student",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "9837450192834",
    name: "Nathaniel Addo",
    email: "n.addo@gmail.com",
    gender: "Male",
    cpdPoints: 41,
    region: "Northern",
    roles: "Licensed",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "6213847501928",
    name: "Priscilla Donkor",
    email: "priscilla.donkor@medghana.org",
    gender: "Female",
    cpdPoints: 23,
    region: "Western",
    roles: "Intern",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "7203948501923",
    name: "Samuel K. Boadu",
    email: "samuel.boadu@sonoghana.com",
    gender: "Male",
    cpdPoints: 18,
    region: "Bono East",
    roles: "Student",
  },
  {
    profileImage: assets.dummy_profile,
    memberId: "2983745092841",
    name: "Adwoa Yeboah",
    email: "adwoa.yeboah@gmail.com",
    gender: "Female",
    cpdPoints: 55,
    region: "Upper East",
    roles: "Licensed",
  },
]
